apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: helm-deploy
  namespace: tekton-pipelines
spec:
  params:
    - name: image
      type: string
      description: Full image name e.g. myuser/devops-java-app-v2
    - name: image-tag
      type: string
      description: Image tag e.g. a1b2c3d
    - name: release-name
      type: string
      description: Helm release name
    - name: namespace
      type: string
      description: Kubernetes namespace
  workspaces:
    - name: helm-source
  steps:
    - name: helm-deploy
      image: alpine/helm:3.9.0
      workingDir: $(workspaces.helm-source.path)
      script: |
        #!/bin/sh
        set -e
        helm upgrade --install $(params.release-name) ./helm-repo \
          --namespace $(params.namespace) \
          --create-namespace \
          --set image.repository=$(params.image) \
          --set image.tag=$(params.image-tag) \
          --wait \
          --timeout 3m