sonar.projectKey=AhmedFathy360_devops-java-app-v2        # the project key you copied from SonarCloud
sonar.organization=Ahmed Fathy      # your SonarCloud organization key
sonar.projectName=DevOps Java App V2       # human readable name, anything you want

# Where is your Java source code?
sonar.sources=src/main/java

# Where are your tests?
sonar.tests=src/test/java

# Where are the compiled classes? (Maven puts them here)
sonar.java.binaries=target/classes

# Where is the JaCoCo XML report? (hint: Maven generates it here)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8